# Generated by Django 5.2.14 on 2026-06-03 07:14

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", reverse_sql="SELECT 1;"),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("in_person", "In Person"),
                            ("video_call", "Video Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField()),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("customer_requirements", models.TextField(blank=True, null=True)),
                ("pain_points", models.TextField(blank=True, null=True)),
                ("pricing_discussion", models.TextField(blank=True, null=True)),
                ("next_steps", models.TextField(blank=True, null=True)),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "competitor_mentions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("interaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_conversation",
                "ordering": ["-interaction_date"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("recording", "Recording"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_actionitem",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["customer"], name="conversatio_custome_4d0826_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["created_by"], name="conversatio_created_612ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["interaction_date"], name="conversatio_interac_6dc958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["sentiment"], name="conversatio_sentime_811cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["ai_status"], name="conversatio_ai_stat_b098b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["is_deleted"], name="conversatio_is_dele_a5d77c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(fields=["status"], name="conversatio_status_1ddbdd_idx"),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["assigned_to"], name="conversatio_assigne_8d2a77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["due_date"], name="conversatio_due_dat_061b2a_idx"
            ),
        ),
    ]
