# Generated by Django 5.2.15 on 2026-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_add_zoho_task_id_to_action_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="gmail_thread_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
