# Generated by Django 5.2.15 on 2026-06-15 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_add_gmail_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="conversations.conversation",
            ),
        ),
    ]
