# Generated by Django 5.2.15 on 2026-06-15 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_add_gmail_thread_id"),
        ("integrations", "0002_add_gmail_credential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="zohocredential",
            name="field_schema_cache",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="zohocredential",
            name="field_schema_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CRMDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("account", "Account")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("extracting", "Extracting"),
                            ("ready", "Ready for Review"),
                            ("submitted", "Submitted"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("extracted_fields", models.JSONField(blank=True, default=dict)),
                ("ai_summary", models.TextField(blank=True)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("confidence", models.JSONField(blank=True, default=dict)),
                ("zoho_record_id", models.CharField(blank=True, max_length=64)),
                ("zoho_note_id", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("edit_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_drafts",
                        to="conversations.attachment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "integrations_crm_draft",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="integration_created_16f313_idx",
                    ),
                    models.Index(
                        fields=["status"], name="integration_status_81c78b_idx"
                    ),
                ],
            },
        ),
    ]
