# Generated by Django 5.2.14 on 2026-06-03 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("contact", "Contact"),
                            ("account", "Account"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "zoho_record_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers_customer",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
                    models.Index(
                        fields=["company"], name="customers_c_company_b97478_idx"
                    ),
                    models.Index(fields=["type"], name="customers_c_type_855833_idx"),
                ],
            },
        ),
    ]
